server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.100:3306/leyou?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.100:8848
  redis:
    host: 192.168.100.100
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  type-aliases-package: com.leyou.order.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml
logging:
  level:
    com.leyou: debug

ly:
  jwt:
    pubKeyPath: D:\software\rsa_key\rsa-key.pub # 公钥地址
    cookie:
      cookieName: LY_TOKEN # cookie名称
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    wx:
      appID: wx8397f8696b538317
      mchID: 1473426802
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
      notifyUrl: http://6saurx.natappfree.cc/api/pay/wx/notify
      payType: NATIVE