server:
  port: 8085
spring:
  application:
    name: sms-service
rocketmq:
  # 指定连接的nameserver注册中心地址
  name-server: 192.168.100.100:9876

ly:
  sms:
    accessKeyID:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    endpoint: 
    signName:  # 签名名称
    verifyCodeTemplate:  # 模板名称
    code: code # 短信模板中验证码的占位符
