server:
  port: 8088
spring:
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.100:8848
  redis:
    host: 192.168.100.100
ly:
  jwt:
    pubKeyPath: D:\software\rsa_key\rsa-key.pub # 公钥地址
    cookie:
      cookieName: LY_TOKEN # cookie名称